"""Config flow — UI for adding TVs/boxes."""
from __future__ import annotations

import logging
from typing import Any

import voluptuous as vol

from homeassistant import config_entries
from homeassistant.const import CONF_HOST, CONF_MAC, CONF_NAME
from homeassistant.data_entry_flow import FlowResult

from .adapters import build_adapter
from .adapters.base import AdapterAuthError, AdapterConnectionError
from .const import (
    CONF_CLIENT_KEY,
    CONF_DEVICE_TYPE,
    DEVICE_TYPE_LABELS,
    DEVICE_TYPE_LG_WEBOS,
    DEVICE_TYPES,
    DOMAIN,
)

_LOGGER = logging.getLogger(__name__)


class UniversalRemoteConfigFlow(config_entries.ConfigFlow, domain=DOMAIN):
    """Stepped UI: pick device type -> enter host/name -> pair if needed."""

    VERSION = 1

    def __init__(self) -> None:
        self._device_type: str | None = None
        self._user_input: dict[str, Any] = {}

    async def async_step_user(self, user_input: dict[str, Any] | None = None) -> FlowResult:
        """Step 1 — pick device type."""
        if user_input is not None:
            self._device_type = user_input[CONF_DEVICE_TYPE]
            if self._device_type == DEVICE_TYPE_LG_WEBOS:
                return await self.async_step_lg_webos()
            # Other device types — placeholders for now.
            return self.async_abort(reason="device_type_not_implemented")

        schema = vol.Schema(
            {
                vol.Required(CONF_DEVICE_TYPE): vol.In(
                    {dt: DEVICE_TYPE_LABELS[dt] for dt in DEVICE_TYPES}
                ),
            }
        )
        return self.async_show_form(step_id="user", data_schema=schema)

    async def async_step_lg_webos(
        self, user_input: dict[str, Any] | None = None
    ) -> FlowResult:
        """Step 2a — LG-specific host/name/MAC, then attempt pairing."""
        errors: dict[str, str] = {}

        if user_input is not None:
            self._user_input = {
                CONF_DEVICE_TYPE: DEVICE_TYPE_LG_WEBOS,
                CONF_HOST: user_input[CONF_HOST],
                CONF_NAME: user_input[CONF_NAME],
                CONF_MAC: user_input.get(CONF_MAC) or None,
                CONF_CLIENT_KEY: None,
            }

            await self.async_set_unique_id(f"{DEVICE_TYPE_LG_WEBOS}_{user_input[CONF_HOST]}")
            self._abort_if_unique_id_configured()

            return await self.async_step_pair()

        schema = vol.Schema(
            {
                vol.Required(CONF_NAME, default="LG TV"): str,
                vol.Required(CONF_HOST): str,
                vol.Optional(CONF_MAC): str,
            }
        )
        return self.async_show_form(
            step_id="lg_webos", data_schema=schema, errors=errors
        )

    async def async_step_pair(self, user_input: dict[str, Any] | None = None) -> FlowResult:
        """Step 3 — pairing handshake (user must accept prompt on TV)."""
        errors: dict[str, str] = {}

        adapter = build_adapter(self._user_input[CONF_DEVICE_TYPE], self._user_input)

        try:
            await adapter.connect()
        except AdapterAuthError:
            errors["base"] = "pair_refused"
        except AdapterConnectionError:
            errors["base"] = "cannot_connect"
        else:
            # Grab the client_key generated by the TV during pairing.
            key = getattr(adapter, "client_key", None)
            await adapter.disconnect()

            if not key:
                errors["base"] = "no_client_key"
            else:
                self._user_input[CONF_CLIENT_KEY] = key
                return self.async_create_entry(
                    title=self._user_input[CONF_NAME],
                    data=self._user_input,
                )

        return self.async_show_form(
            step_id="pair",
            data_schema=vol.Schema({}),
            errors=errors,
            description_placeholders={"host": self._user_input[CONF_HOST]},
        )
